# Generated by Django 2.0.1 on 2020-05-18 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='rate_num',
            field=models.IntegerField(default=0, verbose_name='打分人数'),
        ),
    ]
