# Generated by Django 2.0.1 on 2020-02-27 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageboard',
            name='look_num',
            field=models.IntegerField(default=1, verbose_name='点击数'),
        ),
    ]
