# Generated by Django 2.0.1 on 2020-05-20 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_book_rate_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='rate_num',
            field=models.IntegerField(default=0, verbose_name='评分人数'),
        ),
    ]
