# Generated by Django 2.0.1 on 2020-02-27 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_messageboard_feebback_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageboard',
            name='collect_num',
            field=models.IntegerField(default=1, verbose_name='收藏数'),
        ),
    ]
