# Generated by Django 2.0.1 on 2020-02-27 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_messageboard_collect_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('is_cancel', models.BooleanField(default=False, verbose_name='是否取消')),
                ('message_board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.MessageBoard', verbose_name='留言')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='用户')),
            ],
            options={
                'verbose_name': '收藏留言',
                'verbose_name_plural': '收藏留言',
            },
        ),
    ]
