# Generated by Django 2.0.1 on 2020-02-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_collectboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageboard',
            name='like_num',
            field=models.IntegerField(default=1, verbose_name='点赞数'),
        ),
    ]
