# Generated by Django 2.0.1 on 2020-02-27 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20200227_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageboard',
            name='feebback_num',
            field=models.IntegerField(default=0, verbose_name='回复数'),
        ),
        migrations.AlterField(
            model_name='messageboard',
            name='like_num',
            field=models.IntegerField(default=0, verbose_name='点赞数'),
        ),
    ]
