# Generated by Django 2.0.1 on 2020-02-27 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20200227_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageboard',
            name='collect_num',
            field=models.IntegerField(default=0, verbose_name='收藏数'),
        ),
    ]
