# Generated by Django 2.0.1 on 2020-03-01 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20200227_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectboard',
            name='is_cancel',
        ),
        migrations.AddField(
            model_name='collectboard',
            name='is_collect',
            field=models.BooleanField(default=False, verbose_name='是否收藏'),
        ),
    ]
